media: 
  input: src/media
  output: /src/media
  extensions: 
    - jpg
    - jpeg
    - avif
    - png
    - gif
    - webp
    - mp4
    - mov
    - webm

content: 
  - name: projects
    label: Projects
    type: collection
    path: src/content/projects
    filename: '{fields.title}.md'
    fields: 
      - name: title
        label: Title
        type: string
        required: true
      
      - name: categories
        label: Categories
        type: string
        required: true
      
      - name: year
        label: Year
        type: number
        required: true

      - name: order
        label: Display Order
        type: number
        default: 999
        help: "Lower numbers appear first. Leave at 999 to sort by year."
      
      - name: mediaItems
        label: Media Items
        type: object
        list: true
        required: true
        fields: 
          - name: type
            label: Type
            type: select
            options: 
              values: [Image, Video]
            default: Image
          
          - name: src
            label: Source
            type: file
            required: true
          
          - name: caption
            label: Caption
            type: string
      
      - name: body
        label: Body
        type: rich-text
        required: true

  - name: settings
    label: Site Settings
    type: collection
    path: src/data
    format: json
    filename: header.json
    fields:
      - name: name
        label: Your Name
        type: string
        required: true
      
      - name: tagline
        label: Tagline
        type: string
        required: true
      
      - name: contact
        label: Contact Methods
        type: object
        list: true
        fields:
          - name: label
            label: Label
            type: string
          - name: url
            label: URL
            type: string
          - name: display
            label: Display Text
            type: string
      
      - name: clients
        label: Clients
        type: object
        list: true
        fields:
          - name: name
            label: Client Name
            type: string
            required: true
          - name: url
            label: URL (optional)
            type: string
      - name: experience
        label: Experience
        type: object
        list: true
        fields:
          - name: name
            label: Company Name
            type: string
            required: true
          - name: city
            label: City
            type: string
            required: true
          - name: url
            label: URL (optional)
            type: string
          - name: year
            label: Year(s)
            type: string
            help: "e.g., '2025—' or '2023-2024'"